import Layout from "@/components/Layout";
import css from "@/styles/Home.module.css";
import { useStore } from "../store/store";
import Image from "next/image";
import toast, { Toaster } from "react-hot-toast";

export default () => {
  const CartData = useStore((state) => state.cart.pizzas);
  const removePizza = useStore((state) => state.removePizza);
  const [PaymentMethod, setPaymentMethod] = useState(null)
  const handleRemove = (i) => {
    removePizza(i);
    toast.error("Item Removed");
  };

  const total = () =>
    CartData.pizzas.reduce((a, b) => a + b.quantity * b.price, 0);

  const handleOnDelivery = () => { 
    setPaymentMethod(0);
    typeof window !== "undefined" && localStorage.setItem("total", total());
  }

  return (
    <Layout>
      <Head>
        <title>FUDO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <main>
        <Hero />
        <Services />
        <Menu pizzas={pizzas} />
      </main>

      <div className={css.container}>
        <div className={css.details}>
          <table className={css.table}>
            <thead>
              <th>Pizza</th>
              <th>Name</th>
              <th>Size</th>
              <th>Price</th>
              <th>Quantity</th>
              <th>Total</th>
              <th></th>
            </thead>
            <tbody className={css.tbody}>
              {CartData.pizzas.length > 0 &&
                CartData.pizzas.map((pizza, i) => {
                  const src = urlFor(pizza.image).url();
                  return (
                    <tr key={i}>
                      <td className={css.imageTd}>
                        <Image
                          loader={() => src}
                          alt=""
                          objectFit="cover"
                          unoptimized
                          width={85}
                          height={85}
                        />
                      </td>
                      <td>{pizza.name}</td>
                      <td>
                        {pizza.size === 0
                          ? "Small"
                          : pizza.size === 1
                          ? "Medium"
                          : "Large"}
                      </td>
                      <td>{pizza.price}</td>
                      <td>{pizza.quantity}</td>
                      <td>{pizza.price * pizza.quantity}</td>
                      <td
                        style={{
                          cursor: "pointer",
                          color: "red",
                        }}
                        onClick={() => handleRemove(i)}
                      >
                        x
                      </td>
                    </tr>
                  );
                })}
            </tbody>
          </table>
        </div>

        <div className={css.cart}>
          <span>Cart</span>
          <div className={css.CartDetails}>
            <div>
              <span>Items</span>
              <span>{CartData.pizzas.length}</span>
            </div>
            <div>
              <span>Total</span>
              <span>Rs {total()}</span>
            </div>
          </div>

          <div className={css.buttons}>
            <button className="btn" onClick={handleOnDelivery}>Pay on Delivery</button>
            <button className="btn">Pay Now</button>
          </div>
        </div>
      </div>
      <Toaster />

      <OrderModal
      opened = {PaymentMethod === 0}
      />
    </Layout>
  );
};
